import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import "./globals.css";
import Navbar from "../components/Navbar"; // Import the Navbar component
import Footer from "../components/Footer"; // Import the Footer component
import { AuthProvider } from '@/context/AuthContext'; // Import AuthProvider
import ProgressBar from '../components/ProgressBar'; // Import ProgressBar
import AppContent from '../components/AppContent'; // Import AppContent

const geistSans = GeistSans;

const geistMono = GeistMono;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ProgressBar />
          <AppContent>{children}</AppContent> {/* Wrap content with AppContent */}
        </AuthProvider>
      </body>
    </html>
  );
}